SEARCH_DIR("/usr/lib/aarch64-linux-gnu/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/dynamic_reconfigure/")
SEARCH_DIR("/usr/lib/polkit-1/")
SEARCH_DIR("/usr/lib/xorg/")
SEARCH_DIR("/usr/lib/ogdi/")
SEARCH_DIR("/usr/lib/gnupg/")
SEARCH_DIR("/usr/lib/pulse-16.1+dfsg1/")
SEARCH_DIR("/usr/lib/pppd/")
SEARCH_DIR("/usr/lib/systemd-cron/")
SEARCH_DIR("/usr/lib/NetworkManager/")
SEARCH_DIR("/usr/lib/java-wrappers/")
SEARCH_DIR("/usr/lib/compat-ld/")
SEARCH_DIR("/usr/lib/apparmor/")
SEARCH_DIR("/usr/lib/modprobe.d/")
SEARCH_DIR("/usr/lib/sysusers.d/")
SEARCH_DIR("/usr/lib/tcltk/")
SEARCH_DIR("/usr/lib/apt/")
SEARCH_DIR("/usr/lib/policykit-1/")
SEARCH_DIR("/usr/lib/openssh/")
SEARCH_DIR("/usr/lib/pm-utils/")
SEARCH_DIR("/usr/lib/jvm/")
SEARCH_DIR("/usr/lib/udev/")
SEARCH_DIR("/usr/lib/tasksel/")
SEARCH_DIR("/usr/lib/ispell/")
SEARCH_DIR("/usr/lib/file/")
SEARCH_DIR("/usr/lib/galera/")
SEARCH_DIR("/usr/lib/python3/")
SEARCH_DIR("/usr/lib/ssl/")
SEARCH_DIR("/usr/lib/modules-load.d/")
SEARCH_DIR("/usr/lib/linux/")
SEARCH_DIR("/usr/lib/groff/")
SEARCH_DIR("/usr/lib/chromium/")
SEARCH_DIR("/usr/lib/binfmt.d/")
SEARCH_DIR("/usr/lib/sasl2/")
SEARCH_DIR("/usr/lib/git-core/")
SEARCH_DIR("/usr/lib/mysql/")
SEARCH_DIR("/usr/lib/raspi-config/")
SEARCH_DIR("/usr/lib/apache2/")
SEARCH_DIR("/usr/lib/raspberrypi-sys-mods/")
SEARCH_DIR("/usr/lib/gnome-settings-daemon-3.0/")
SEARCH_DIR("/usr/lib/emacsen-common/")
SEARCH_DIR("/usr/lib/debug/")
SEARCH_DIR("/usr/lib/tmpfiles.d/")
SEARCH_DIR("/usr/lib/bfd-plugins/")
SEARCH_DIR("/usr/lib/genmsg/")
SEARCH_DIR("/usr/lib/cgi-bin/")
SEARCH_DIR("/usr/lib/jni/")
SEARCH_DIR("/usr/lib/firmware/")
SEARCH_DIR("/usr/lib/dbus-1.0/")
SEARCH_DIR("/usr/lib/php/")
SEARCH_DIR("/usr/lib/blt2.5/")
SEARCH_DIR("/usr/lib/runit-helper/")
SEARCH_DIR("/usr/lib/man-db/")
SEARCH_DIR("/usr/lib/valgrind/")
SEARCH_DIR("/usr/lib/linux-image-6.6.20+rpt-rpi-v8/")
SEARCH_DIR("/usr/lib/menu-cache/")
SEARCH_DIR("/usr/lib/rc-gui/")
SEARCH_DIR("/usr/lib/raspi-firmware/")
SEARCH_DIR("/usr/lib/systemd/")
SEARCH_DIR("/usr/lib/girepository-1.0/")
SEARCH_DIR("/usr/lib/kernel/")
SEARCH_DIR("/usr/lib/udisks2/")
SEARCH_DIR("/usr/lib/gcc/")
SEARCH_DIR("/usr/lib/userconf-pi/")
SEARCH_DIR("/usr/lib/locale/")
SEARCH_DIR("/usr/lib/klibc/")
SEARCH_DIR("/usr/lib/fpc/")
SEARCH_DIR("/usr/lib/cmake/")
SEARCH_DIR("/usr/lib/python3.11/")
SEARCH_DIR("/usr/lib/genpy/")
SEARCH_DIR("/usr/lib/gnupg2/")
SEARCH_DIR("/usr/lib/cups/")
SEARCH_DIR("/usr/lib/gvfs/")
SEARCH_DIR("/usr/lib/init/")
SEARCH_DIR("/usr/lib/gold-ld/")
SEARCH_DIR("/usr/lib/pkgconfig/")
SEARCH_DIR("/usr/lib/aspell/")
SEARCH_DIR("/usr/lib/console-setup/")
SEARCH_DIR("/usr/lib/avr/")
SEARCH_DIR("/usr/lib/roslib/")
SEARCH_DIR("/usr/lib/pam.d/")
SEARCH_DIR("/usr/lib/ifupdown/")
SEARCH_DIR("/usr/lib/linux-kbuild-6.6.31+rpt/")
SEARCH_DIR("/usr/lib/linux-image-6.6.31+rpt-rpi-v8/")
SEARCH_DIR("/usr/lib/mc/")
SEARCH_DIR("/usr/lib/linux-kbuild-6.6.20+rpt/")
SEARCH_DIR("/usr/lib/linux-image-6.6.31+rpt-rpi-2712/")
SEARCH_DIR("/usr/lib/notification-daemon/")
SEARCH_DIR("/usr/lib/X11/")
SEARCH_DIR("/usr/lib/p7zip/")
SEARCH_DIR("/usr/lib/modules/")
SEARCH_DIR("/usr/lib/printer-driver-escpr/")
SEARCH_DIR("/usr/lib/libtorch-test/")
SEARCH_DIR("/usr/lib/firewalld/")
SEARCH_DIR("/usr/lib/sysctl.d/")
SEARCH_DIR("/usr/lib/lsb/")
SEARCH_DIR("/usr/lib/lazarus/")
SEARCH_DIR("/usr/lib/linux-image-6.6.20+rpt-rpi-2712/")
SEARCH_DIR("/usr/lib/dpkg/")
SEARCH_DIR("/usr/lib/mime/")
SEARCH_DIR("/usr/lib/environment.d/")
SEARCH_DIR("/usr/lib/vnc/")
SEARCH_DIR("/usr/lib/genlisp/")
SEARCH_DIR("/usr/lib/gencpp/")
SEARCH_DIR("/usr/lib/terminfo/")
SEARCH_DIR("/usr/lib/gcc/aarch64-linux-gnu/12/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/industrialstuff/lib/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/Sdpo/SdpoJoystick/lib/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/gifanim/lib/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/lazcontrols/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/freetype/lib/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/")
SEARCH_DIR("/root/.lazarus/onlinepackagemanager/packages/synapse40.1/lib/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/")
SEARCH_DIR("/usr/lib/lazarus/2.2.6/packager/units/aarch64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/httpd22/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/zlib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/proj4/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/ncurses/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/bzip2/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-report/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gdbint/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-extra/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/sdl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/oracle/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pxlib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/symbolic/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/mad/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-sdo/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/ldap/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/cdrom/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fftw/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-json/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libusb/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/googleapi/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/httpd24/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libcurl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-pdf/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-sound/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-js/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/uuid/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libxml2/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-web/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/ggi/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/mysql/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-async/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/ibase/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/chm/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/newt/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/x11/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pthreads/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gdbm/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/odbc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/jni/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/syslog/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/sqlite/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/openssl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/opengles/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/regexpr/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/lua/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/utmp/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libsee/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-console/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/oggvorbis/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-registry/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libgc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/bfd/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/xforms/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/cairo/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-passrc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/users/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/postgres/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gnutls/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/imagemagick/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/ptc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/aspell/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/svgalib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libenet/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/dbus/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/tplylib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/odata/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/zorba/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-extra/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rsvg/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fppkg/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libmagic/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libtar/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libcups/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/tcl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/unzip/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libgd/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/opengl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pcap/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fastcgi/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/modplug/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libvlc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-generics/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/numlib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/dblib/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/iconvenc/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libpng/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/openal/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-process/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/a52/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fv/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fpindexer/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libfontconfig/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-db/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fpmkunit/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/libmicrohttpd/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-stl/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/hash/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/hermes/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/vcl-compat/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-unicode/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gmp/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/dts/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-res/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/fpc/3.2.2/")
INPUT(
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/cprt0.o
/usr/lib/aarch64-linux-gnu/crti.o
/usr/lib/gcc/aarch64-linux-gnu/12/crtbegin.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/gerenciador.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/gerenciador.or
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/system.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/lnfodwrf.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/exeinfo.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/strings.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/fpintres.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/objpas.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/cthreads.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/interfaces.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/forms.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/main.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/setmain.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/toolsfalar.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/funcoes.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnetbase.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnetvisual.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/LazSerialPort.o
/root/.lazarus/onlinepackagemanager/packages/gifanim/lib/aarch64-linux/pkg_gifanim.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/zcomponent.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/config.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/banco.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/cfgspeak.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/cfgbanco.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/bloqueio.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/opamostragem.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/imp.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/imp_elgini9.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/imp_generico.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/imp_qr203.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/cfgimp.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/etiquetar.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/pesqpacientes.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/pesqtipoexames.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/chatgpt.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/toolsouvir.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/toolsver.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/splash.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/log.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/linux.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/baseunix.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/unix.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/unixtype.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/initc.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/dl.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/unixutil.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/ctypes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/cwstring.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/dynlibs.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/unixcp.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2disableliboverlay.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2int.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/classes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/sysutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/types.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/typinfo.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/rtlconsts.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/errors.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/sysconst.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/math.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/x11/xlib.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/x11/x.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/gdk2x.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/gdk2pixbuf.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/gtk2.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/gdk2.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/glib2.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/pango.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lmessages.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclproc.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclintf.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lcltype.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/dialogs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/controls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclstrconsts.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/graphics.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/menus.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/themes.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/buttons.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/stdctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/checklst.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/comctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/extctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclplatformdef.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/interfacebase.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wslclclasses.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wscontrols.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2winapiwindow.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2globals.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2proc.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2def.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2fontcache.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2extra.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2msgqueue.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/graphtype.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/graphmath.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazfileutils.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazutf8.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/dynhasharray.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/maps.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/integerlist.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazloggerbase.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laztracer.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazutilities.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazstringutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/x11/xrender.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/cairo/cairo.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/atk.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/fpcadds.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazclasses.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazmethodlist.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/strutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/gettext.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz_avl_tree.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazutilsstrconsts.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/fileutil.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/utf8process.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazsysutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpimage.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/intfgraphics.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadbmp.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpwritebmp.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/bmpcomn.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadpng.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpwritepng.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadtiff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpwritetiff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fptiffcmn.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclversion.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/icnstypes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpimgcmn.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/pngcomn.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/zstream.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/zbase.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/gzio.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/hash/crc.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/zdeflate.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/zinflate.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/trees.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/adler.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/infblock.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/infutil.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/infcodes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/inftrees.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/paszlib/inffast.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazversion.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/contnrs.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpcanvas.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadpnm.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpwritepnm.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadjpeg.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpwritejpeg.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpreadgif.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lresources.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclrescache.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsreferences.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/clipping.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jpeglib.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdapimin.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdatasrc.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdapistd.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jmorecfg.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdeferr.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jinclude.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jerror.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jmemmgr.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdmarker.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdinput.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcomapi.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jmemnobs.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdmaster.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdcolor.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdsample.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdpostct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jddctmgr.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdphuff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdhuff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdcoefct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdmainct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jquant1.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jquant2.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdmerge.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jidctfst.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jidctint.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jidctflt.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jidctred.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcapistd.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcapimin.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jdatadst.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcparam.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcinit.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcmarker.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcphuff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jchuff.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcmaster.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jccolor.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcsample.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcprepct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcdctmgr.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jccoefct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jcmainct.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jfdctint.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jfdctfst.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/pasjpeg/jfdctflt.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/variants.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazconfigstorage.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/dynqueue.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/varutils.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/avglvltree.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazdbglog.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/syncobjs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/tmschema.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/fgl.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/masks.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-process/process.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-process/pipes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl/termio.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/buttonpanel.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclclasses.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/clipbrd.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lcltaskdialog.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/uitypes.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/custapp.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/customtimer.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/actnlist.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/helpintfs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/imglist.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/singleinstance.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fpimgcanv.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/fppixlcanv.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/pixtools.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-image/ellipses.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsimglist.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsproc.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsfactory.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/propertystorage.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/rttiutils.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsmenus.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazlogger.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/chm/fasthtmlparser.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/system.uitypes.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsforms.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/imagelistcache.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/textstrings.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/extendedstrings.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsstdctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsbuttons.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/popupnotifier.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsextctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsdialogs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wschecklst.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/toolwin.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wscomctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wstoolwin.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/gtk2/gtk2ext.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/extdlgs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclmessageglue.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2debug.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/calendar.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/calcform.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wscalendar.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsextdlgs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/messages.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lclmemmanager.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsprivate.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/uriparser.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wscontrols.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazlinkedlist.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsfactory.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsstdctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wschecklst.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2themes.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/spin.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/grids.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/pairsplitter.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsspin.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/htmldefs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/maskedit.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/dynamicarray.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz2_xmlcfg.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lcsvutils.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/lazfilecache.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz2_dom.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz2_xmlread.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz2_xmlwrite.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/laz2_xmlutils.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsgrids.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wspairsplitter.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsbuttons.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wscalendar.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wscomctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsdialogs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsextctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsextdlgs.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsforms.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsgrids.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsimglist.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsmenus.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wsspin.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2wspairsplitter.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/unitywsctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2cellrenderer.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/gtk2/gtk2listviewtreemodel.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/lazserial.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/brobotico.o
/home/mmm/projetos/maurinsoft/doctor/software/raspberry/lib/aarch64-linux/aguarde.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/lazsynaser.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedit.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-json/fpjson.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-db/db.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-json/jsonparser.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/regexpr/regexpr.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/lazsynimmbase.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/stdactns.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittypes.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditsearch.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditkeycmds.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmousecmds.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmiscprocs.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditpointclasses.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synbeautifier.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarks.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkup.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkuphighall.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupbracket.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupwordgroup.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupctrlmouselink.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupspecialline.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupselection.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmarkupspecialchar.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittextbase.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/lazsynedittext.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittextbuffer.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditlines.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittexttrimmer.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittexttabexpander.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittextdoublewidthchars.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditfoldedview.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syngutterbase.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syngutter.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditmiscclasses.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedithighlighter.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/lazsyntextarea.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syntextdrawer.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedittextbidichars.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synguttercodefolding.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syngutterchanges.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syngutterlinenumber.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synguttermarks.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syngutterlineoverview.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-registry/registry.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/inifiles.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-registry/xmlreg.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/dom.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlread.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlwrite.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/dtdmodel.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlreader.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmltextreader.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/syneditstrconst.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/lazsyneditmousecmdstypes.o
/usr/lib/lazarus/2.2.6/components/synedit/units/aarch64-linux/gtk2/synedithighlighterfoldbase.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/graphutil.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lazcanvas.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lazregions.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/fmtbcd.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/maskutils.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-db/dbconst.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-json/jsonscanner.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-json/jsonreader.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnetcomponents.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnet.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lclnet.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/ltelnet.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lftp.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lsmtp.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lhttp.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnetssl.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/levents.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lcommon.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/netdb.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-extra/sockets.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lcontrolstack.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-base/base64.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lmimewrapper.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lmimestreams.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lhttputil.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lstrbuffer.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/openssl/openssl.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZConnection.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZDataset.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZAbstractConnection.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZTransaction.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZClasses.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcDbLib.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMySql.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPostgreSql.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcInterbase6.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcFirebird.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSqLite.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcOracle.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcASA.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSQLAnywhere.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPooled.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcODBCCon.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZCompatibility.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZSysUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcIntfs.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZDatasetUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZFormatSettings.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZExceptions.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcConnection.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcLogging.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainDbLibDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZTokenizer.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZGenericSqlAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZMessages.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZEncoding.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/rtl-objpas/dateutils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFastCode.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZGenericSqlToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZVariant.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZCollections.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZSelectSchema.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcResultSetMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainLoader.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcProperties.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcCachedResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcCache.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcGenericResolver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcDbLibStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcDbLibMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZSybaseToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZSybaseAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcDbLibUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcDbLibResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainMySqlDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMySqlStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZMySqlToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMySqlUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMySqlMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZMySqlAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcMySqlResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZMatchPattern.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainPostgreSqlDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPostgreSqlStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPostgreSqlUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPostgreSqlMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZPostgreSqlToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZPostgreSqlAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcPostgreSqlResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainFirebirdInterbaseDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcInterbase6Utils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcFirebirdInterbase.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZInterbaseToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZInterbaseAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcInterbaseFirebirdMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcInterbase6Statement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcInterbase6ResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainFirebird.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcFirebirdStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcFirebirdResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainSqLiteDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZSqLiteToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZSqLiteAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSqLiteStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSqLiteUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSqLiteMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSqLiteResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainOracleDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZOracleToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZOracleAnalyser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcOracleStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcOracleUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcOracleMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcOracleResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainASADriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcASAMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcASAStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcASAUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcASAResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainSQLAnywhere.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSQLAnywhereStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSQLAnywhereResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcSQLAnywhereUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zplain/aarch64-linux/ZPlainODBCDriver.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZODBCToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcODBCMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcODBCStatement.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcODBCUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcODBCResultSet.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZDatasetParam.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZExpression.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZAbstractRODataset.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSqlUpdate.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSqlProcessor.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSqlStrings.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZExprParser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZExprToken.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZVariables.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctions.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctionsMath.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctionsDateTime.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctionsStrings.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctionsConvert.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZFunctionsOther.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSequence.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZAbstractDataset.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZMemTable.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zparsesql/aarch64-linux/ZScriptParser.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zdbc/aarch64-linux/ZDbcXmlUtils.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcore/aarch64-linux/ZBase64.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZAbstractTable.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/propedits.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/lazsynafpc.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/lazsynautil.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/editbtn.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/valedit.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/filectrl.o
/usr/lib/lazarus/2.2.6/components/lazcontrols/lib/aarch64-linux/gtk2/checkboxthemed.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/stringhashlist.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/objinspstrconsts.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/propeditutils.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/frmselectprops.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/stringspropeditdlg.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/keyvalpropeditdlg.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/collectionpropeditform.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/filefilterpropeditor.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/pagespropeditdlg.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/idewindowintf.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/groupededit.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/calendarpopup.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/timepopup.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/shellctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/wsshellctrls.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/ideimagesintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/ideoptionsintf.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/lazideintf.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lazhelphtml.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/baseideintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/compoptsintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/projectintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/ideexterntoolintf.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/ideopteditorintf.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/srceditorintf.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/lazhelpintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/macrointf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/macrodefintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/newitemintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/projpackintf.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/buildstrconsts.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/editorsyntaxhighlighterdef.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/idecommands.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/texttools.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/formeditingintf.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/objectinspector.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/idedialogs.o
/usr/lib/lazarus/2.2.6/components/buildintf/units/aarch64-linux/lazmsgworker.o
/usr/lib/lazarus/2.2.6/components/lazutils/lib/aarch64-linux/compwriterpas.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/componenteditors.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/unitresources.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/lazstringgridedit.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/checklistboxeditordlg.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/checkgroupeditordlg.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/componentreg.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/arrow.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/industrialbase.o
/usr/lib/lazarus/2.2.6/components/lazcontrols/lib/aarch64-linux/gtk2/treefilteredit.o
/usr/lib/lazarus/2.2.6/components/lazcontrols/lib/aarch64-linux/gtk2/listfilteredit.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/idehelpintf.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/componenttreeview.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/oifavoriteproperties.o
/usr/lib/lazarus/2.2.6/components/ideintf/units/aarch64-linux/gtk2/changeparentdlg.o
/root/.lazarus/onlinepackagemanager/packages/LazSerial/lib/aarch64-linux/lazserialsetup.o
/root/.lazarus/onlinepackagemanager/packages/synapse40.1/lib/aarch64-linux/synaser.o
/root/.lazarus/onlinepackagemanager/packages/industrialstuff/lib/aarch64-linux/mknob.o
/root/.lazarus/onlinepackagemanager/packages/industrialstuff/lib/aarch64-linux/lednumber.o
/root/.lazarus/onlinepackagemanager/packages/industrialstuff/lib/aarch64-linux/indgnoumeter.o
/root/.lazarus/onlinepackagemanager/packages/industrialstuff/lib/aarch64-linux/AdvLed.o
/root/.lazarus/onlinepackagemanager/packages/synapse40.1/lib/aarch64-linux/synafpc.o
/root/.lazarus/onlinepackagemanager/packages/synapse40.1/lib/aarch64-linux/synautil.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/dbctrls.o
/usr/lib/lazarus/2.2.6/lcl/units/aarch64-linux/dbgrids.o
/root/.lazarus/onlinepackagemanager/packages/gifanim/lib/aarch64-linux/gifanim.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lwebserver.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lmimetypes.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lprocess.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lspawnfcgi.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/ltimer.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lthreadevents.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/fastcgi_base.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lfastcgi.o
/root/.lazarus/onlinepackagemanager/packages/lnet/lazaruspackage/lib/aarch64-linux/lnetvisualreg.o
/usr/lib/lazarus/2.2.6/packager/units/aarch64-linux/lazaruspackageintf.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZConnectionGroup.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZEventListener.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZGroupedConnection.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZIBEventAlerter.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZPgEventAlerter.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSqlMetadata.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZSqlMonitor.o
/root/.lazarus/onlinepackagemanager/packages/zeosdbo/packages/lazarus/lib/zcomponent/aarch64-linux/ZStoredProcedure.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-web/fphttpclient.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/openssl/opensslsockets.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/ssockets.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-web/httpdefs.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/resolve.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-web/httpprotocol.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/sslsockets.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/fcl-net/sslbase.o
/usr/lib/aarch64-linux-gnu/fpc/3.2.2/units/aarch64-linux/openssl/fpopenssl.o
)
INPUT(
-lpthread
-ldl
-lgdk-x11-2.0
-lgtk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/aarch64-linux-gnu/12/crtend.o
/usr/lib/aarch64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
